package com.pepsi.onenetwork.models.destination;

import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import lombok.Getter;
import lombok.Setter;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(Include.NON_EMPTY)
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ssZ")
@Getter
@Setter
@SuppressWarnings("unused")
public class StockTransferOrder implements Serializable {

	private static final long serialVersionUID = 1L;
	private String actionName;
	private String owningOrgEnterpriseName;
	private String owningOrgName;
	private String shipFromSiteEnterpriseName;
	private String shipFromSiteOrganizationName;
	private String shipFromSiteName;
	private String shipFromAddressStreet1;
	private String shipFromAddressStreet2;
	private String shipFromAddressCity;
	private String shipFromAddressState;
	private String shipFromAddressZip;
	private String shipFromAddressCountry;
	private String shipToSiteEnterpriseName;
	private String shipToSiteOrganizationName;
	private String shipToSiteName;
	private String shipToAddressStreet1;
	private String shipToAddressStreet2;
	private String shipToAddressCity;
	private String shipToAddressState;
	private String shipToAddressZip;
	private String shipToAddressCountry;
	private String orderMgmtOrgEnterpriseName;
	private String orderMgmtOrgName;
	private String orderNumber;
	private String lineNumber;
	private String genericItemName;
	private String specificItemName;
	private String itemName;
	private String itemEnterpriseName;
	private String lineType;
	private double requestQuantity;
	private String quantityUOM;
	private double lineAmount;
	private String currency;
	private Date requestDeliveryDate;
	private Date requestShipDate;
	private double unitPrice;
	private String transModeName;
	private String fobCode;
	private String fobPoint;
	private String buyerCode;
	private String plannerCode;
	private String loadType;
	private String billToAddressStreet1;
	private String billToAddressStreet2;
	private String billToAddressCity;
	private String billToAddressState;
	private String billToAddressZip;
	private String billToAddressCountry;
	private String purchasingAddressStreet1;
	private String purchasingAddressStreet2;
	private String purchasingAddressCity;
	private String purchasingAddressState;
	private String purchasingAddressZip;
	private String purchasingAddressCountry;
	private String remitToAddressStreet1;
	private String remitToAddressStreet2;
	private String remitToAddressCity;
	private String remitToAddressState;
	private String remitToAddressZip;
	private String remitToAddressCountry;
	private String rmaNumber;
	private String requisitionNumber;
	private String requisitionRequestingOrgEnterpriseName;
	private String requisitionRequestingOrgName;
	private int priority;
	private String shipWithGroupRef;
	private double totalAmount;
	private String orderCurrency;
	private String omoOrderNumber;
	private String wmsOrderNumber;
	private String packingQuantity;
	private String packingUOM;
	private String extCreationDate;
	private String plannerNotes;
	private String requestScheduleAction;
	private String requestScheduleNumber;
	private String deliveryScheduleNumber;
	private String buyingAgent1EnterpriseName;
	private String buyingAgent1Name;
	private String buyingAgent2EnterpriseName;
	private String buyingAgent2Name;
	private String buyingAgent3EnterpriseName;
	private String buyingAgent3Name;
	private String buyingAgent4EnterpriseName;
	private String buyingAgent4Name;
	private String productGroupLevel1Name;
	private String productGroupLevel2Name;
	private String productGroupLevel3Name;
	private String productGroupLevel4Name;
	private String productGroupLevel5Name;
	private String productGroupProductGroupEnterpriseName;
	private String productGroupProductGroupTypeName;
	private String sellingAgent1EnterpriseName;
	private String sellingAgent1Name;
	private String sellingAgent2EnterpriseName;
	private String sellingAgent2Name;
	private String sellingAgent3EnterpriseName;
	private String sellingAgent3Name;
	private String sellingAgent4EnterpriseName;
	private String sellingAgent4Name;
	private String packageName;
	private String packageEnterpriseName;
	private String packageItemQuantity;
	private String packageItemUOM;
	private String packingResourceName;
	private String packingResourceOrgEnterpriseName;
	private String packingResourceOrgName;
	private String extPackingResourceName;
	private boolean isEmergency;
	private boolean sExpedite;
	private String omsEquipment;
	private String requestIncoDate;
	private String promiseIncoDate;
	private String requestMinItemExpiryDate;
	private String promiseMinItemExpiryDate;
	private String programEnterpriseName;
	private String programName;
	private String requestIncoDateStartDate;
	private String requestIncoDateEndDate;
	private String promiseIncoDateStartDate;
	private String promiseIncoDateEndDate;
	private String references;
	private String requisitionLineLineNumber;
	private String requisitionLineRequestingOrgEnterpriseName;
	private String requisitionLineRequestingOrgName;
	private String lineRequisitionNumber;
	private String orderClassification;
}